#! /usr/bin/env python

import json, sys, pprint

for filename in sys.argv[1:]:
  longest = 0
  widest = 0
  long_item = None
  wide_item = None
  try:
    for row in json.load(open(filename)):
      try:
        length = len(str(row))
        if length > longest:
          longest = length
          long_item = row
      except:
        pass
      try:
        length = len(row['columns'])
        if length > widest:
          widest = length
          wide_item = row
      except:
        pass
    try: print filename, widest, wide_item['key'], longest, long_item['key']
    except: pass
  except: pass
